# Generated by Django 3.1.7 on 2021-05-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('dob', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.IntegerField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField(max_length=10)),
                ('bio', models.CharField(max_length=250)),
                ('imcid', models.CharField(max_length=20)),
                ('regno', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=70)),
                ('online_profile_link', models.CharField(max_length=150)),
                ('yoe', models.IntegerField(max_length=5)),
                ('language', models.CharField(max_length=50)),
                ('available', models.IntegerField(max_length=4)),
                ('fees', models.IntegerField(max_length=10)),
            ],
        ),
    ]
