# Generated by Django 3.1.7 on 2021-05-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient', '0003_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
