# Generated by Django 3.1.7 on 2021-05-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_patient', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
